config/routes.rb
TwitterApp::Application.routes.draw do
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions

  get "signup" => "users#new", :as => "signup"
  resources :users

  get "search/index"

  root :to => "search#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :encrypt_password

  attr_accessor :password

  attr_accessible :email, :name, :password, :password_confirmation

  validates :name,
    :presence => true

  validates :email,
    :presence => true,
    :uniqueness => true

  validates :password,
    :presence => true ,
    :confirmation => true,
    :length => {:minimum => 5},
    :on => :create
 

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine::generate_salt
      self.password_hash = BCrypt::Engine::hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine::hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authorize

  # Makes method available in views
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless current_user
      redirect_to login_path
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:q].present?
      rpp = params[:rpp] || DEFAULT_NB_RESULTS
      @tweets = Twitter.search(params[:q], :rpp => rpp).results
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create]

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "You successfully logged in"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to login_path, :notice => "You successfully signed up. Please log in."
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
</head>
<body>

  <%= render 'shared/header' %>

  <% flash.each do |name, msg| %>
  <div class="container">
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <%= content_tag :div, msg if msg.is_a?(String) %>
    </div>
  </div>
  <%end %>

  <%= yield %>

</body>
</html>

app/views/search/_form.html.erb
<%= form_tag(search_index_path, :method => "get", :id => 'search-form') do %>

  <div class="row">
    <div class="span3">
      <%= label_tag(:q, "Search for") %>
      <%= text_field_tag(:q, params[:q], :class => 'input', :placeholder => 'Type here...') %>
    </div>

    <div class="span3">
      <%= label_tag(:rpp, "Number of results") %>
      <%= select_tag(:rpp, options_for_select([DEFAULT_NB_RESULTS, 10, 20, 50], params[:rpp])) %>
    </div>
  </div>

  <div class="row">
    <div class="span3">
      <%= button_tag("Search", :type => 'submit', :disabled_with => 'Searching...', :class => 'btn btn-primary') %>
      <%= button_tag("Reset", :type => 'reset', :class => 'btn') %>
    </div>
  </div>
<% end %>

app/views/search/_tweets_list.haml
- if @tweets && @tweets.size > 0
  %table.table.table-striped
    %thead
      %tr
        %th User
        %th Tweet
        %th Date
    %tbody
      - @tweets.each do |status|
        %tr
          %td
            = status.from_user
          %td
            = status.text
          %td.date
            = status.created_at.strftime(DATE_FORMAT_LONG)

app/views/search/index.html.haml
.container
  .row
    .span6
      %h2 Search Tweets
      = render 'form'

  = render 'tweets_list'

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">TwitterApp</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Search", root_path %></li>
        </ul>
      </div>

      <div class="">
        <ul class="nav pull-right">
          <% if current_user %>
          <li><%= link_to "Hello #{current_user.name}" %></li>
          <li><%= link_to "Log out", logout_path %></li>
          <% else %>
          <li><%= link_to "Sign up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div class="">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p><%= f.button "Sign up", :type => 'submit', :class => "btn btn-primary" %></p>

  <br/>
  <p>Already registered? <%= link_to "Log in", login_path %> </p>
<% end %>

app/views/users/new.html.haml
.container
  .row
    .span6
      %h2 Sign up
      = render "form"